### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ernado** [golangci/golangci-lint#1027]
Hi! Currently most of maintainers and project author are out of capacity to actively address issues.
I will update this status weekly until further notice.
 ![Gaining traction](https://img.shields.io/static/v1?label=status&message=limited%20activity&color=yellow)

I will try to explicitly allocate some resources, but I'm not sure that it will be enough.
While this issue is still pinned, new feature requests and PR's with new features (+ new linters, etc) are mostly frozen. I will continue efforts to stabilize project via fixing bugs, OOM-s and other major issues.
**Please don't close existing PR's**, they will be reviewed eventually.

Any help with issue triage and debugging (e.g. investigating issues and providing draft solutions) will be very appreciated. 

Sorry!

UPD: Known major issues

- [x] https://github.com/golangci/golangci-lint/issues/1012 (very high memory usage, please disable *unused* linter for workaround)
- [x] https://github.com/golangci/golangci-lint/issues/1026 (homebrew version is out of date)
- [x] https://github.com/golangci/golangci-lint/issues/995 (doomed failed prerequisites error with cold cache)

**Comment by ernado** [comment]
UPD: I've allocated some time and started maintaining. Also I'm looking into ways of golangci.com revival for OSS projects.

Please treat the current situation with understanding, I'm still gaining traction.

**Comment by nashikb** [comment]
FYI, you'll probably want to make sure tests pass before committing to master. In theory everyone should be using a tag, but a lot of people don't and a broken master branch isn't ideal either way.

**Comment by ernado** [comment]
Currently master is OK, FOSSA is just reporting some kind of false-positive.

![image](https://user-images.githubusercontent.com/866677/79974684-6eff1280-84a2-11ea-9036-1e2ce1b99945.png)

**Comment by ernado** [comment]
Project is stabilized as per v1.25.0, please upgrade.

**Comment by agnivade** [comment]
Thanks @ernado. Much appreciated ! If you would be open to external sponsors for your project so that you can allocate more time, feel free to let me know if I can help somehow.

**Comment by jirfag** [comment]
My current focus is to fix the lack of maintainers and their time. What's changed:
1. I've built the [guide for contributors](https://golangci-lint.run/contributing/quick-start/).
2. All issues created the first time by a contributor get a help from a bot `boring-cyborg` with a link to the contribution guide.
3. All contributors are invited into GolangCI organization into [this team](https://github.com/orgs/golangci/teams/team). This team has write access to `golangci-lint` repository.
To ensure stability I've made a `master` branch protected and required CI checks to pass and approved code review before merging.
So, any team member can approve pull request and merge them when checks pass.

![image](https://user-images.githubusercontent.com/4648736/82153424-0ff9a700-9870-11ea-9f93-53f6c2f3ddd8.png)

**Comment by jirfag** [comment]
@twpayne @theckman @iwankgb @bombsimon @ryancurrah @dixonwille @viktorasm @tetafro @uudashr @barthr @LukeShu @sayboras @lopezator @NiseVoid @zchee @tommy-muehle @nakabonne @ksoichiro @ewohltman @JohnStarich @vovapi @tdakkota @saschagrunert @rung @proton-ab @kortschak @jfrabaute @gsora @elliots @diegs @cezarsa @cblecker @beono @benpaxton-hf @be-b10g @ashanbrown @aneeshusa @amenzhinsky @a8m @to6ka @matoous 

thank you for all your contributions. I've invited you into the GolangCI organization (check it [here](https://github.com/orgs/golangci/invitation)). After accepting the invitation you can label issues, review pull requests, and merge approved pull requests in the `golangci-lint` repo.
The contributing guide is [here](https://golangci-lint.run/contributing/quick-start/).

**Comment by ldez** [comment]
The problem is fixed: the maintenance of golangci-lint is now stable.
