### ISSUE TITLE
meta: golangci-automator doesn't work anymore

### ISSUE THREAD

**Issue by JohnTitor** [golangci/golangci-lint#2852]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Until https://github.com/golangci/golangci-lint/pull/2652#issuecomment-1072471315, the bot welcomed a new contributor and invited to the org, but since https://github.com/golangci/golangci-lint/pull/2746#issuecomment-1088869603, the bot didn't comment even if it was merged (here's a brief list of targeted PRs: https://github.com/golangci/golangci-lint/pulls?q=is%3Apr+is%3Amerged+%22your+first+Pull+Request%22).
I think some part of https://github.com/golangci/golangci-lint/tree/master/.github/peril should have the cause, but the log isn't available and I cannot investigate further.
Could you check it and revive the bot?

### Version of golangci-lint

(this is a meta issue.)

### Configuration file

(this is a meta issue.)

### Go environment

(this is a meta issue.)

### Verbose output of running

(this is a meta issue.)

### Code example or link to a public repository

(this is a meta issue.)
